name: Log group
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "::group::Show envitoment variables"
        printenv
        echo "::endgroup::"
      - run: echo "not group log"