name: Log group
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Show envitoment variables"
          printenv
          echo "::endgroup::"
          echo "not group log"
      - run: echo "other step log"