name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWRORD }}
    steps:
      - run: echo "${PASSWORD}" # ログマスクされる
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # ログマスクされない